version: '3.9'

services:
 postgres:
  container_name: postgres_container
  env_file: .db.env
  ports:
   - "5430:5432"
#  volumes:
#   - ./pgdata:/var/lib/postgresql/data
  build:
   context: .
   dockerfile: db.Dockerfile
  restart: unless-stopped

volumes:
 pgdata:
  driver: local
