"""Database creation

Revision ID: c889c3cc89f9
Revises: 
Create Date: 2024-11-25 19:29:54.913724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from models import Role, User
from config import Settings


# revision identifiers, used by Alembic.
revision = 'c889c3cc89f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###
    op.bulk_insert(
        Role.__table__, [
            {
                "id": 1,
                "name": Settings.first_role
            }
        ]
    )
    op.bulk_insert(
        Role.__table__, [
            {
                "id": 2,
                "name": Settings.second_role
            }
        ]
    )

    op.bulk_insert(
        User.__table__, [
            {
                "login": Settings.first_user_login,
                "password": Settings.first_user_password,
                "role": Settings.first_user_role
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    Session = sessionmaker(bind=op.get_bind())
    session = Session()

    roles = session.query(Role).all()
    if roles:
        for role in roles:
            session.delete(role)
        session.commit()

    user = session.query(User).filter_by(user_id=1).first()
    if user:
        session.delete(user)
        session.commit()

    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
